services:
  naruto:
    container_name: naruto
    build: .
    image: naruto-dev:latest
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    restart: always